### ISSUE TITLE
Problem running mod

### ISSUE THREAD

**Issue by dodo4928** [Hummel009/LOTR-Extended#1]
Hello, when i start lotr extended 2 with mod lord of the rings + v36.11 the game will crash after a while. What version of lord of the rings lotr extended 2 requires

**Comment by dodo4928** [comment]
please help me

**Comment by Aces-and-Jacks** [comment]
> please help me

So from experimenting, not sure if you did this already, this only works on lotr 36.10. Again not sure if you already knew this just trying to help with what version it works on

**Comment by Hummel009** [comment]
Sorry for long answer, I didn't notice issues here. I updated the mod, it should work well.
